### ISSUE TITLE
Application won't syntheze

### ISSUE THREAD

**Issue by Vampy707** [lexkoro/GameTTS#10]
Hi guys,

I did the Game TTS instatlaoin as described, but it won't sythesize the text or file.
Python is installed with the instalation of the application. Can't find a missing command or file.
Is this issue known to anyone? Maybe I just to inexperienced with python.

**Comment by lexkoro** [comment]
So, when you press synthesize nothing happens?

**Comment by Vampy707** [comment]
Yes a loading singh appears an no error, no data, no report what is missing or what didn't work.

**Comment by lexkoro** [comment]
Not sure, did you maybe install it under C: and it has no write permission to output the files?

**Comment by Vampy707** [comment]
Shame on me! It was an permissions related issue, thaks for the quick help! Awesome work!
