### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by ctrl1lur** [lexkoro/GameTTS#12]
Unable to launch the GameTTS.exe just gives me this error under Win10

`Install GameTTS Requirements.
Error Installing GameTTS: Message = Das System kann die angegebene Datei nicht finden
    bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start()
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei GameTTS.Program.RunPythonScript(String python, String command) in C:\Users\Alex\source\repos\GameTTS-Dev\GameTTS-Dev\Program.cs:Zeile 52.
   bei GameTTS.Program.Main(String[] args) in C:\Users\Alex\source\repos\GameTTS-Dev\GameTTS-Dev\Program.cs:Zeile 126.
`

**Comment by TheFurryDevil** [comment]
The directory path you run the GameTTS.exe in must not contain any spaces
