### ISSUE TITLE
List more dependencies

### ISSUE THREAD

**Issue by LordKobra** [lexkoro/GameTTS#14]
I tried to start the executable, but nothing happened. So i started the main.py from an environment, using the dependency list provided.

There were several more things required, before i could get the program to run.

-Installation of ffmpeg and adding it to PATH https://www.ffmpeg.org/download.html#build-windows
-Installation of Visual Studio Build Tools 2014 or newer (i think it was necessary for gruut) https://visualstudio.microsoft.com/visual-cpp-build-tools/
-I don't have edge and eel couldn't find chrome, so i had to add this to main.py:
`import eel.browsers`
`eel.browsers.set_path('chrome', 'my/path/to/chrome.exe')`
...
`eel.start(page, mode="chrome", **eel_kwargs)`

Now everything works.

PS: Do you have a discord account or similar, where one can write PMs? GitHub Issues is not really the right place.

**Comment by lexkoro** [comment]
Hi, thanks for the tips.

ffmpeg shouldn't be a requirement. At least I don't have it installed and it still works. What was the error message here?
The same goes for the build tools if you use the embedded Python, but I'm not sure about that one. If you install it manually then yes it is required for gruut.

I think the main reason why the executable did not work was the last point with it not finding a browser to open the app.

My discord tag is Resser#9231

**Comment by LordKobra** [comment]
I guess you could be right about that. ffmpeg was probably just a warning, but gruut had a real error. Maybe the error did not exist in the preinstalled version, the terminal closed before i could see.

The issue with the main install was, i only got a Windows sound and saw python not terminating, but there was no output, even when run in console. But running main.py resulted in a window telling me "microsoft-edge:https://.." application not found with exactly the same sound i heard earlier. I guess the window got suppressed earlier and resulted in python not terminating, because it was waiting for a response. Maybe an alternative could be searching for chrome or firefox or the default browser reference, if that's possible.
