### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by DrVoltai** [lexkoro/GameTTS#15]
I got an error message while installing:

> Error Installing GameTTS: Message = Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
    bei System.Net.WebClient.DownloadFile(Uri address, String fileName)
   bei System.Net.WebClient.DownloadFile(String address, String fileName)
   bei GameTTS.Program.DownloadTTSModel(String url, String currentPath) in C:\Users\Alex\source\repos\GameTTS-Dev\GameTTS-Dev\Program.cs:Zeile 35.
   bei GameTTS.Program.Main(String[] args) in C:\Users\Alex\source\repos\GameTTS-Dev\GameTTS-Dev\Program.cs:Zeile 132.

**Comment by lexkoro** [comment]
Seems like it can't download the trained model.
Which OS are you using?
Maybe try again.

**Comment by CalebderGrosse** [comment]
same problem i use win 10

**Comment by lexkoro** [comment]
Could be a firewall issue blocking the connection to Github, so you can't download the model.

**Comment by CalebderGrosse** [comment]
welche der 3 zip ist den nun di, die man nutzten soll?
die GameTTS_0.01, GameTTS_0.02 oder GameTTS_main ?
Oder bauen die aufeinander auf?

**Comment by CalebderGrosse** [comment]
i try it with GameTTS_main and get this:

Install GameTTS Requirements.
Error Installing GameTTS: Message = Das System kann die angegebene Datei nicht finden
    bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start()
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei GameTTS.Program.RunPythonScript(String python, String command) in C:\Users\Alex\source\repos\GameTTS-Dev\GameTTS-Dev\Program.cs:Zeile 52.
   bei GameTTS.Program.Main(String[] args) in C:\Users\Alex\source\repos\GameTTS-Dev\GameTTS-Dev\Program.cs:Zeile 126.

**Comment by ctrl1lur** [comment]
> 

Thanks for the heads up. I also use WIN 10 Pro. Tried to manually download and place the file -> same error.
Doesn´t seem to be a firewall issue, disabled it and still got the exact same error message

**Comment by ctrl1lur** [comment]
After moving the files to another partition it could install without a hitch

**Comment by MaxKissgen** [comment]
> After moving the files to another partition it could install without a hitch

This was the case for me as well. I moved the folder from `C:` to `F:`, where `C:` is an SSD with the operating system on it and `F:` is a HDD.
