### ISSUE TITLE
Application launches without UI

### ISSUE THREAD

**Issue by Ecco1924** [lexkoro/GameTTS#16]
The application launches without the UI shown in the readme.

The only windows opening up are these two browser instances:

![grafik](https://user-images.githubusercontent.com/18574326/149674924-a4826f80-fd80-441d-9bfd-441c8f36f63c.png)

**Comment by lexkoro** [comment]
Looks like port 8080 is already in use.

Open the main.py and change the port https://github.com/lexkoro/GameTTS/blob/edb513b779b57474b7e0c5885e5f62556527252c/GameTTS/main.py#L133
to something else like 9090.

**Comment by Ecco1924** [comment]
Thank you, that solved it!
