### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by prussiablade** [lexkoro/GameTTS#2]
Hi, what`s the problem here? Installation went through except for the following note. Thanks for help.

python : WARNING: You are using pip version 21.2.4; however, version 21.3 is available.
At C:\GameTTS\install.ps1:21 char:5
+     python -m pip install -r .\requirements.txt
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: You ar...3 is available.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
You should consider upgrading via the 'C:\GameTTS\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by lexkoro** [comment]
Yeah I made some changes today, might have been in a broken state.

I've tried making it more accessible by wrapping the PowerShell scripts into an exe.

Would you mind giving it a try? https://github.com/lexkoro/GameTTS/releases/tag/v0.0.1

**Comment by lexkoro** [comment]
Can you try running as Administrator?
Otherwise I will try to get rid of PowerShell....

**Comment by prussiablade** [comment]
Ich schreib mal deutsch... mittlerweile konnte ich die Installation zum laufen bekommen, dazu musste der Schreibschutz des gesamten GameTTS-Ordners aufgehoben werden und zusätzlich an den Dateien "install.ps1", "run.ps1" und "GameTTS.exe" per Rechtsklick: Eigenschaften/Sicherheit auf zulassen geklickt werden.

![image](https://user-images.githubusercontent.com/92627740/137640124-cda39dde-b100-4e9c-b4e2-a5d746847d08.png)

So lief die Installation per .exe dann erstmalig ohne Fehlermeldung durch... leider startet die Anwendung trotzdem nicht:

PS C:\GameTTS\bin> C:\GameTTS\bin\run.ps1
python : C:\Program Files\Python38\python.exe: can't open file '.\main.py': [Errno 2] No such file or directory
At C:\GameTTS\bin\run.ps1:8 char:5
+     python .\main.py
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by prussiablade** [comment]
Hi, ich noch mal. Du solltest in die Beschreibung der Installation reinnehmen, dass "Chrome" installiert sein muss und als Standardbrowser eingestellt ist. Wenn dann zusätzlich keine Firewall mehr im Weg ist, läuft das Programm auch :dancing_men: 

Bestehen Pläne das Tool auch auf anderen Browsern kompatibel zu machen?

Ansonsten sehr feines Programm das ungeahnte Möglichkeiten verschafft :)

**Comment by mindactuate** [comment]
Great! I’ll test the new installation process tonight. Do you need help with something? It’s a great project and I’d be happy to help. :)

**Comment by mindactuate** [comment]
0.0.2 works great! 👍
