### ISSUE TITLE
Linux and Terminal Version

### ISSUE THREAD

**Issue by NathanaelMangold** [lexkoro/GameTTS#20]
We were able to "convert" the code to run from other python scripts. This worked without any issues on Windows 10. However trying it on Linux it does not work at all. Is there any way to make it work on Linux and a (properly) terminal callable version?

**Comment by lexkoro** [comment]
Hey, 
do you get any errors?  
What Version of GameTTS are you using? This one or the 1.1.5 shared in the WoG Forum?

> Is there any way to make it work on Linux and a (properly) terminal callable version?
Generally it should work on Linux,  pretty sure some people are already using it there. 
Also I tested it myself before and it worked.

 Yes I plan to implement a CLI, but since it is a hobby project, it might take some time.

**Comment by NathanaelMangold** [comment]
I am starting the "main.py". The UI starts without any issues and does not show any errors. I used the latest version from this Repo from the Releases. Should be Version 0.0.2
![grafik](https://user-images.githubusercontent.com/41338825/172129486-4175d319-9b85-44e3-8f6f-7dedbdb41dec.png)

In the console i can see the following:
pi@raspberrypi:~/Downloads/GameTTS-main/GameTTS $ python3 main.py
/home/pi/.local/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: module compiled against API version 0xe but this version of numpy is 0xd (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
INFO:root:Loaded checkpoint '/home/pi/Downloads/GameTTS-main/GameTTS/vits/model/G_600000.pth'
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:32] "GET /index.html HTTP/1.1" 200 22396 0.003419
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:32] "GET /css/all.css HTTP/1.1" 200 73836 0.002086
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:32] "GET /css/font-google.css HTTP/1.1" 200 9353 0.001662
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:32] "GET /css/mdb.min.css HTTP/1.1" 200 304015 0.002640
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:32] "GET /js/mdb.min.js HTTP/1.1" 200 238313 0.003339
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:32] "GET /eel.js HTTP/1.1" 200 6110 0.002363
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:32] "GET /js/jquery-3.6.0.min.js HTTP/1.1" 200 107959 0.002239
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
DEBUG:geventwebsocket.handler:Attempting to upgrade connection
DEBUG:geventwebsocket.handler:WebSocket request accepted, switching protocols
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:33] "GET /webfonts/fa-solid-900.woff2 HTTP/1.1" 200 78394 0.003569
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:33] "GET /resource/json-mapping/game_map.json HTTP/1.1" 200 279 0.001431
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-06 10:53:33] "GET /resource/json-mapping/0_sorted.json HTTP/1.1" 200 1537 0.001960
DEBUG:gruut.utils:Successfully imported gruut_lang_de
DEBUG:gruut.utils:Successfully imported gruut_lang_de
DEBUG:gruut.phonemize:Loading CRF g2p model from /home/pi/.local/lib/python3.9/site-packages/gruut_lang_de/g2p/model.crf
DEBUG:gruut.phonemize:Connecting to /home/pi/.local/lib/python3.9/site-packages/gruut_lang_de/lexicon.db
DEBUG:gruut.phonemize:Attempting to load feature names
DEBUG:gruut.phonemize:Guessing pronunciations for Token(text='ein', features={}) with CRF
DEBUG:gruut.phonemize:Guessing pronunciations for Token(text='blindtext', features={}) with CRF
DEBUG:gruut.phonemize:Guessing pronunciations for Token(text='sprachausgabe', features={}) with CRF
Illegal instruction

**Comment by lexkoro** [comment]
```
/home/pi/.local/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: module compiled against API version 0xe but this version of numpy is 0xd (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:67.)
_dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
```
I think it might be a problem with numpy and raspberrypi 

Maybe this https://github.com/freqtrade/freqtrade/issues/4281#issue-797549742 helps

**Comment by NathanaelMangold** [comment]
So I could fix the Numpy issue, but it still does not work.
This is the Log:
`
pi@raspberrypi:~/Downloads/GameTTS-main/GameTTS $ python main.py
INFO:root:Loaded checkpoint '/home/pi/Downloads/GameTTS-main/GameTTS/vits/model/G_600000.pth'
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:22] "GET /index.html HTTP/1.1" 200 22396 0.004268
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /css/all.css HTTP/1.1" 200 73836 0.002831
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /css/font-google.css HTTP/1.1" 200 9353 0.001609
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /eel.js HTTP/1.1" 200 6110 0.001934
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /css/mdb.min.css HTTP/1.1" 200 304015 0.003338
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /js/mdb.min.js HTTP/1.1" 200 238313 0.002613
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /js/jquery-3.6.0.min.js HTTP/1.1" 200 107959 0.002738
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
DEBUG:geventwebsocket.handler:Attempting to upgrade connection
DEBUG:geventwebsocket.handler:WebSocket request accepted, switching protocols
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /webfonts/fa-solid-900.woff2 HTTP/1.1" 200 78394 0.002657
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /resource/json-mapping/game_map.json HTTP/1.1" 200 279 0.002624
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
INFO:geventwebsocket.handler:127.0.0.1 - - [2022-06-08 19:26:23] "GET /resource/json-mapping/0_sorted.json HTTP/1.1" 200 1537 0.003329
DEBUG:gruut.utils:Successfully imported gruut_lang_de
DEBUG:gruut.utils:Successfully imported gruut_lang_de
DEBUG:gruut.phonemize:Loading CRF g2p model from /home/pi/.local/lib/python3.9/site-packages/gruut_lang_de/g2p/model.crf
DEBUG:gruut.phonemize:Connecting to /home/pi/.local/lib/python3.9/site-packages/gruut_lang_de/lexicon.db
DEBUG:gruut.phonemize:Attempting to load feature names
DEBUG:gruut.phonemize:Guessing pronunciations for Token(text='ein', features={}) with CRF
DEBUG:gruut.phonemize:Guessing pronunciations for Token(text='blindtext', features={}) with CRF
DEBUG:gruut.phonemize:Guessing pronunciations for Token(text='sprachausgabe', features={}) with CRF
Illegal instruction
`

**Comment by lexkoro** [comment]
Yeah not sure then, maybe someone else with a raspberry pi can help.

**Comment by DanBmh** [comment]
You can find a working Linux setup (with docker) [here](https://gitlab.com/DANBER/Jaco-GameTTS/-/blob/master/Containerfile). I'm using it as TTS for _Jaco_ so there is some extra code in it which you can drop if you don't need it.
