### ISSUE TITLE
Possible mistake in install.ps1

### ISSUE THREAD

**Issue by R5on11c** [lexkoro/GameTTS#5]
You might have made a mistake in the install.ps1 in the commit 82c230c739161051426c9d91fa3af561ae04a35f "Update install.ps1 " line 14

in this line you wrote:
`virtualenv .venv`
which makes the installation fail. After replacing it with the original:
`python -m virtualenv .venv`
from before the script worked flawlessly.

You might want to revert this specific change.

**Comment by lexkoro** [comment]
Yeah I made the change because `python -m virtualenv .venv` wasn't working with python3.10 anymore for whatever reason...
I will revert the change and pin the python version to 3.9 for now...
